### ISSUE TITLE
As a developer I want to be able to customize all the endpoints paths

### ISSUE THREAD

**Issue by mihaita-tinta** [mihaita-tinta/spring-boot-starter-webauthn#1]
The library should allow users to change the default paths

```yaml
webauthn:
  endpoints:
    registrationStartPath: /registration/start
    registrationAddPath: /registration/add
    registrationFinishPath: /registration/finish
    assertionStartPath: /assertion/start
    assertionFinishPath: /assertion/finish
```
